### ISSUE TITLE
docker-compose http communication issue

### ISSUE THREAD

**Issue by wdvr** [fhircast/sandbox#38]
docker-compose up does not work out of the box. 

Steps to reproduce:

1. run `docker-compose up`
2. navigate the client at localhost:5000
3. make a subscription, with default hub URL, any string for events/topic

Client error:
```
client_1  | 2019-05-04 14:59:03.4906|8|ERROR|Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher|Failed to invoke hub method 'subscribe'. System.Net.Http.HttpRequestException: Cannot assign requested address ---> System.Net.Sockets.SocketException: Cannot assign requested address
client_1  |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

Hub and subscriber cannot talk to each other. See [this](https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/225) issue for more info, seems to be that localhost is not supported to connect from container to container due to the way docker-compose sets up the network.

**Comment by lbergnehr** [comment]
When using `hub` as the host for the Hub the call makes it to the hub but then the callback from the Hub to the WebSubClient server breaks for the same reason since that is hard coded to `localhost` right now.

I wonder what the best way to get around this would be. One would be to add those parameters in the UI (the callback url). Another would be to inject the callback url that the client should send to the Hub using env vars.

**Comment by wdvr** [comment]
@lbergnehr see pull request. Not sure if this is the best way to do this in .Net, let me know if you had another idea in mind.
